use alloc::vec::Vec;

use sha2::{Digest, Sha256};

use crate::cryptomat::{
	CryptoAlg,
	Pk,
	PwHash,
	PwHashComposer,
	SignK,
	SignKeyComposer,
	SignKeyPair,
	Sk,
	SkComposer,
	StaticKeyPair,
	SymKeyGen,
	VerifyK,
};
use crate::error::Error;
use crate::{ClientRandomValue, DeriveAuthKeyForAuth, DeriveMasterKeyForAuth, HashedAuthenticationKey};

pub struct RegisterOutPut<P: Pk, V: VerifyK>
{
	//info about the raw master key (not the encrypted by the password!)
	pub master_key_alg: &'static str,

	//from key derived
	pub client_random_value: ClientRandomValue,
	pub hashed_authentication_key_bytes: HashedAuthenticationKey,
	pub encrypted_master_key: Vec<u8>,
	pub encrypted_master_key_alg: &'static str,
	pub derived_alg: &'static str,

	//the key pairs incl. the encrypted secret keys
	pub public_key: P,
	pub encrypted_private_key: Vec<u8>,
	pub keypair_encrypt_alg: &'static str,
	pub verify_key: V,
	pub encrypted_sign_key: Vec<u8>,
	pub keypair_sign_alg: &'static str,
}

pub struct LoginDoneOutput<S: Sk, Si: SignK>
{
	pub private_key: S,
	pub sign_key: Si,
}

pub struct ChangePasswordOutput
{
	pub client_random_value: ClientRandomValue,
	pub hashed_authentication_key_bytes: HashedAuthenticationKey,
	pub encrypted_master_key: Vec<u8>,
	pub encrypted_master_key_alg: &'static str,
	pub derived_alg: &'static str,
	pub old_auth_key: DeriveAuthKeyForAuth,
}

pub struct ResetPasswordOutput
{
	pub master_key_alg: &'static str,
	pub client_random_value: ClientRandomValue,
	pub hashed_authentication_key_bytes: HashedAuthenticationKey,
	pub encrypted_master_key: Vec<u8>,
	pub encrypted_master_key_alg: &'static str,
	pub derived_alg: &'static str,
	pub encrypted_private_key: Vec<u8>,
	pub encrypted_sign_key: Vec<u8>,
}

pub struct PrepareLoginOutput
{
	pub master_key_encryption_key: DeriveMasterKeyForAuth,
	pub auth_key: DeriveAuthKeyForAuth,
}

/**
# Register a new user

Every user got a master key, every other user key is encrypted by this master key.

The master key is encrypted by a derived key from password. The password turned into two different keys via a password hash.
The first key is the derived key and encrypts the master key. The second key is the authentication for the server.
Only this key gets send to the server not the password.

A public / private encryption key pair and a sign / verify key pair get created too.

Both private and sign key gets encrypted by the master key.

<br>

## For key update:
Just register the user again with a password, it should be the same password for usability, but it can a different password too.
Then login again and encrypt everything what was encrypted by the old keys with the new keys
(e.g. group keys (encrypted by public key), or direct encrypted data).
*/
pub fn register<S: SymKeyGen, St: StaticKeyPair, Sign: SignKeyPair, H: PwHashComposer>(
	password: &str,
) -> Result<RegisterOutPut<St::PublicKey, Sign::VerifyKey>, Error>
{
	//1. create master key
	let master_key = S::generate()?;

	//2. create static pub/pri key pair for encrypt and decrypt
	let (sk, public_key) = St::generate_static_keypair()?;

	//3. create sign key pair for sign and verify
	let (sign_k, verify_key) = Sign::generate_key_pair()?;

	let encrypted_private_key = sk.encrypt_by_master_key(&master_key)?;
	let encrypted_sign_key = sign_k.encrypt_by_master_key(&master_key)?;

	let (client_random_value, hashed_authentication_key_bytes, encrypted_master_key, encrypted_master_key_alg) =
		H::get_hasher().derived_keys_from_password(password.as_bytes(), &master_key)?;

	Ok(RegisterOutPut {
		master_key_alg: master_key.get_alg_str(),
		derived_alg: client_random_value.get_alg_str(),
		client_random_value,
		hashed_authentication_key_bytes,
		encrypted_master_key,
		encrypted_master_key_alg,
		encrypted_sign_key,
		verify_key,
		keypair_sign_alg: sign_k.get_alg_str(),
		encrypted_private_key,
		public_key,
		keypair_encrypt_alg: sk.get_alg_str(),
	})
}

/**
# Start the login process

The salt was generated by the server when the user first interact with the server.
*/
pub fn prepare_login<H: PwHashComposer>(password: &str, salt: &[u8], derived_encryption_key_alg: &str) -> Result<PrepareLoginOutput, Error>
{
	let (master_key_encryption_key, auth_key) = H::get_from_alg(derived_encryption_key_alg)?.derive_keys_for_auth(password.as_bytes(), salt)?;

	Ok(PrepareLoginOutput {
		master_key_encryption_key,
		auth_key,
	})
}

/**
# End the login process

Get all information about the current used login keys
*/
pub fn done_login<SkC: SkComposer, SiC: SignKeyComposer>(
	derived_encryption_key: &DeriveMasterKeyForAuth, //the value from prepare_login
	encrypted_master_key: &[u8],                     //as base64 encoded string from the server
	encrypted_private_key: &[u8],
	keypair_encrypt_alg: &str,
	encrypted_sign_key: &[u8],
	keypair_sign_alg: &str,
) -> Result<LoginDoneOutput<SkC::SecretKey, SiC::Key>, Error>
{
	//decrypt the master key from the derived key from password
	let master_key = derived_encryption_key.get_master_key(encrypted_master_key)?;

	//decode the private keys to the enums to use them later
	let private_key = SkC::decrypt_by_master_key(&master_key, encrypted_private_key, keypair_encrypt_alg)?;
	let sign_key = SiC::decrypt_by_master_key(&master_key, encrypted_sign_key, keypair_sign_alg)?;

	Ok(LoginDoneOutput {
		private_key,
		sign_key,
	})
}

/**
# Prepare Password change

before calling this function make a request to the login api endpoint with the username
to get the salt from the api
if the old pw was wrong this will check in the api later after this function

get the old auth key from @see prepare_login()
with the old pw and the old salt

decrypt the master key with the old pw (because it is stored in the client but encrypted)

use the function @see derivedKeysFromPassword with the new pw and the decrypted master key
to create the new client random value, the new encrypted master key and the new hashed authkey

send the return data back to the server
*/
pub fn change_password<H: PwHashComposer>(
	old_pw: &str,
	new_pw: &str,
	old_salt: &[u8],
	encrypted_master_key: &[u8],
	derived_encryption_key_alg: &str,
) -> Result<ChangePasswordOutput, Error>
{
	//first make a request to login endpoint -> prepareLogin() with the username to get the salt
	//get the old auth key
	let prepare_login_output = prepare_login::<H>(old_pw, old_salt, derived_encryption_key_alg)?;

	//decrypt the master key with the old pw.
	let master_key = prepare_login_output
		.master_key_encryption_key
		.get_master_key(encrypted_master_key)?;

	//encrypt the master key with the new pw and create a new salt with a new random value
	//the 2nd check is necessary because master key from different alg can have different length
	let (client_random_value, hashed_authentication_key_bytes, encrypted_master_key, encrypted_master_key_alg) =
		H::get_from_alg(derived_encryption_key_alg)?.derived_keys_from_password(new_pw.as_bytes(), &master_key)?;

	Ok(ChangePasswordOutput {
		derived_alg: client_random_value.get_alg_str(),
		client_random_value,
		hashed_authentication_key_bytes,
		encrypted_master_key,
		encrypted_master_key_alg,
		old_auth_key: prepare_login_output.auth_key,
	})
}

/**
# Reset the users password

Only works if the user still got access to the decrypted private key and the decrypted sign key (which are encrypted by the old password).

1. create a new master key like register()
2. encrypt the private and sign keys with the new master key. Use here the alg from the actual selected feature
3. finally encrypt the new master key by the new password

## Security hint:
- the server still awaits a valid auth token when sending the reset password request
- an attacker needs access to the decrypted private key, decrypted sign key and the auth token
*/
pub fn password_reset<S: SymKeyGen, H: PwHashComposer>(
	new_pw: &str,
	decrypted_private_key: &impl Sk,
	decrypted_sign_key: &impl SignK,
) -> Result<ResetPasswordOutput, Error>
{
	//1. create a new master key (because the old key was encrypted by the forgotten password and can't be restored)
	let master_key = S::generate()?;

	//2. encrypt the private and the sign key with the new master key
	let encrypted_private_key = decrypted_private_key.encrypt_by_master_key(&master_key)?;
	let encrypted_sign_key = decrypted_sign_key.encrypt_by_master_key(&master_key)?;

	//3. encrypt the new master key with the new password
	let (client_random_value, hashed_authentication_key_bytes, encrypted_master_key, encrypted_master_key_alg) =
		H::get_hasher().derived_keys_from_password(new_pw.as_bytes(), &master_key)?;

	Ok(ResetPasswordOutput {
		master_key_alg: master_key.get_alg_str(),
		derived_alg: client_random_value.get_alg_str(),
		client_random_value,
		hashed_authentication_key_bytes,
		encrypted_master_key,
		encrypted_master_key_alg,
		encrypted_private_key,
		encrypted_sign_key,
	})
}

pub struct SafetyNumber<'a, Vk: VerifyK>
{
	pub verify_key: &'a Vk,
	pub user_info: &'a str,
}

/**
Creates a safety number in byte of a given verify key and additional user information like the user id or username.

## combined number

To create a combination of two identities set for user_2 another SafetyNumberUser struct.
Make sure to keep the order of user_1 and user_2 on the other user too, otherwise the number will not be the same.
 */
pub(crate) fn safety_number<Vk: VerifyK>(user_1: SafetyNumber<Vk>, user_2: Option<SafetyNumber<Vk>>) -> Vec<u8>
{
	let mut hasher = Sha256::new();

	user_1.verify_key.create_hash(&mut hasher);

	hasher.update(user_1.user_info.as_bytes());

	if let Some(u_2) = user_2 {
		u_2.verify_key.create_hash(&mut hasher);

		hasher.update(u_2.user_info.as_bytes());
	}

	let number_bytes = hasher.finalize();

	number_bytes.to_vec()
}

#[cfg(test)]
mod test
{
	use core::str::from_utf8;

	use super::*;
	use crate::{PwHasherGetter, SecretKey, SignKey, SymmetricKey, VerifyKey};

	#[test]
	fn test_register()
	{
		let password = "abc*èéöäüê";

		//register should not panic because we only use internally values!
		let _ = register::<SymmetricKey, SecretKey, SignKey, PwHasherGetter>(password).unwrap();
	}

	#[test]
	fn test_login()
	{
		//the normal register
		let password = "abc*èéöäüê";

		let out = register::<SymmetricKey, SecretKey, SignKey, PwHasherGetter>(password).unwrap();

		//and now try to log in
		//normally the salt gets calc by the api
		let salt_from_rand_value = out.client_random_value.generate_salt("");

		let prep_login_out = prepare_login::<PwHasherGetter>(password, &salt_from_rand_value, out.derived_alg).unwrap();

		//try to decrypt the master key
		let login_out = done_login::<SecretKey, SignKey>(
			&prep_login_out.master_key_encryption_key, //the value comes from prepare login
			&out.encrypted_master_key,
			&out.encrypted_private_key,
			out.keypair_encrypt_alg,
			&out.encrypted_sign_key,
			out.keypair_sign_alg,
		)
		.unwrap();

		//try to encrypt / decrypt with the keypair
		let public_key = out.public_key;

		let text = "Hello world üöäéèßê°";
		let encrypted = public_key.encrypt(text.as_bytes()).unwrap();
		let decrypted = login_out.private_key.decrypt(&encrypted).unwrap();
		let decrypted_text = from_utf8(&decrypted).unwrap();

		assert_eq!(decrypted_text, text);

		//try sign and verify
		let verify_key = out.verify_key;

		let data_with_sign = login_out.sign_key.sign(&encrypted).unwrap();
		let (_data, verify_res) = verify_key.verify(&data_with_sign).unwrap();

		assert!(verify_res);
	}

	#[test]
	fn test_pw_change()
	{
		//the normal register
		let password = "abc*èéöäüê";
		let new_password = "abcdfg";

		let out = register::<SymmetricKey, SecretKey, SignKey, PwHasherGetter>(password).unwrap();

		//normally the salt gets calc by the api
		//for all different random value alg
		//classic way here because when generating salt we will move the value, but we need the old salt for pw change and after for comparing the output
		let salt_from_rand_value = out.client_random_value.generate_salt("");

		let pw_change_out = change_password::<PwHasherGetter>(
			password,
			new_password,
			&salt_from_rand_value,
			&out.encrypted_master_key,
			out.derived_alg,
		)
		.unwrap();

		//must be different because it is encrypted by a new password
		assert_ne!(out.encrypted_master_key, pw_change_out.encrypted_master_key);

		//the decrypted master key must be the same
		//first get the master key which was encrypted by the old password
		let prep_login_old = prepare_login::<PwHasherGetter>(password, &salt_from_rand_value, out.derived_alg).unwrap();

		//2nd get the master key which was encrypted by the new password
		let new_salt = pw_change_out.client_random_value.generate_salt("");
		let prep_login_new = prepare_login::<PwHasherGetter>(new_password, &new_salt, pw_change_out.derived_alg).unwrap();

		let key_old = prep_login_old
			.master_key_encryption_key
			.get_master_key(&out.encrypted_master_key)
			.unwrap();
		let key_new = prep_login_new
			.master_key_encryption_key
			.get_master_key(&pw_change_out.encrypted_master_key)
			.unwrap();

		assert_eq!(key_old.as_ref(), key_new.as_ref());
	}

	#[test]
	fn test_password_reset()
	{
		let password = "abc*èéöäüê";
		let out = register::<SymmetricKey, SecretKey, SignKey, PwHasherGetter>(password).unwrap();

		let salt_from_rand_value = out.client_random_value.generate_salt("");

		let prep_login_out = prepare_login::<PwHasherGetter>(password, &salt_from_rand_value, out.derived_alg).unwrap();

		//try to decrypt the master key
		let login_out = done_login::<SecretKey, SignKey>(
			&prep_login_out.master_key_encryption_key, //the value comes from prepare login
			&out.encrypted_master_key,
			&out.encrypted_private_key,
			out.keypair_encrypt_alg,
			&out.encrypted_sign_key,
			out.keypair_sign_alg,
		)
		.unwrap();

		//reset the password
		let new_password = "123";

		let password_reset_out = password_reset::<SymmetricKey, PwHasherGetter>(new_password, &login_out.private_key, &login_out.sign_key).unwrap();

		//test if we can log in with the new password
		let salt_from_rand_value = password_reset_out.client_random_value.generate_salt("");

		let prep_login_out_pw_reset = prepare_login::<PwHasherGetter>(new_password, &salt_from_rand_value, password_reset_out.derived_alg).unwrap();

		//try to decrypt the master key
		let login_out_pw_reset = done_login::<SecretKey, SignKey>(
			&prep_login_out_pw_reset.master_key_encryption_key, //the value comes from prepare login
			&password_reset_out.encrypted_master_key,
			&password_reset_out.encrypted_private_key,
			out.keypair_encrypt_alg,
			&password_reset_out.encrypted_sign_key,
			out.keypair_sign_alg,
		)
		.unwrap();

		assert_ne!(out.encrypted_master_key, password_reset_out.encrypted_master_key);

		match (login_out.private_key, login_out_pw_reset.private_key) {
			(SecretKey::Ecies(sk), SecretKey::Ecies(sk1)) => {
				assert_eq!(sk.as_ref(), sk1.as_ref())
			},
			(SecretKey::Kyber(sk), SecretKey::Kyber(sk1)) => {
				assert_eq!(sk.as_ref(), sk1.as_ref())
			},
			(SecretKey::EciesKyberHybrid(sk), SecretKey::EciesKyberHybrid(sk1)) => {
				let (x, k) = sk.get_raw_keys();
				let (x1, k1) = sk1.get_raw_keys();

				assert_eq!(x, x1);
				assert_eq!(k, k1);
			},
			_ => panic!("Keys not the same format"),
		}
	}

	fn create_dummy_user_for_safety_number() -> (VerifyKey, LoginDoneOutput<SecretKey, SignKey>)
	{
		let password = "abc*èéöäüê";
		let out = register::<SymmetricKey, SecretKey, SignKey, PwHasherGetter>(password).unwrap();

		let salt_from_rand_value = out.client_random_value.generate_salt("");

		let prep_login_out = prepare_login::<PwHasherGetter>(password, &salt_from_rand_value, out.derived_alg).unwrap();

		//try to decrypt the master key
		let login_out = done_login::<SecretKey, SignKey>(
			&prep_login_out.master_key_encryption_key, //the value comes from prepare login
			&out.encrypted_master_key,
			&out.encrypted_private_key,
			out.keypair_encrypt_alg,
			&out.encrypted_sign_key,
			out.keypair_sign_alg,
		)
		.unwrap();

		(out.verify_key, login_out)
	}

	#[test]
	fn test_safety_number()
	{
		let (user_1_key, _user_1) = create_dummy_user_for_safety_number();
		let (user_2_key, _user_2) = create_dummy_user_for_safety_number();

		let number = safety_number(
			SafetyNumber {
				verify_key: &user_1_key,
				user_info: "abc",
			},
			None,
		);

		let number_1 = safety_number(
			SafetyNumber {
				verify_key: &user_1_key,
				user_info: "abc",
			},
			Some(SafetyNumber {
				verify_key: &user_2_key,
				user_info: "abc",
			}),
		);

		let number_2 = safety_number(
			SafetyNumber {
				verify_key: &user_2_key,
				user_info: "abc",
			},
			Some(SafetyNumber {
				verify_key: &user_1_key,
				user_info: "abc",
			}),
		);

		assert_eq!(number.len(), 32);
		assert_eq!(number_1.len(), 32);
		assert_eq!(number_2.len(), 32);

		assert_ne!(number_1, number_2);
	}
}
