name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  core-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-core-${{ hashFiles('**/Cargo.lock') }}

      - name: Core tests
        run: cargo test --package sentc-crypto-core test

  std-keys-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-core-${{ hashFiles('**/Cargo.lock') }}

      - name: Std keys tests
        run: cargo test --package sentc-crypto-std-keys --lib test --features=full

  fips-keys-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-core-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

      - name: Install OpenSSL 3.3
        run: |
          wget https://www.openssl.org/source/openssl-3.3.0.tar.gz
          tar -xzf openssl-3.3.0.tar.gz
          cd openssl-3.3.0
          ./config fips
          make
          sudo make install

      - name: Set OpenSSL environment variables
        run: |
          echo "/usr/local/lib64" | sudo tee /etc/ld.so.conf.d/openssl.conf
          sudo ldconfig
          export OPENSSL_DIR=/usr/local/ssl
          export OPENSSL_LIB_DIR=/usr/local/lib64
          export OPENSSL_INCLUDE_DIR=/usr/local/include

      - name: Verify OpenSSL version
        run: |
          openssl version -a

      - name: Fips keys tests
        run: cargo test --package sentc-crypto-fips-keys --lib test --features=full

  crypto-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-crypto_default-${{ hashFiles('**/Cargo.lock') }}

      - name: Crypto default tests
        run: cargo test --package sentc-crypto --lib test --features=server,export

  crypto-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-crypto_rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Crypto rust tests
        run: cargo test --package sentc-crypto --lib test --features=server

  crypto-light-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-crypto_rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Crypto light default tests
        run: cargo test --package sentc-crypto-light --lib test --features=export

  crypto-light-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-crypto_rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Crypto light rust tests
        run: cargo test --package sentc-crypto-light --lib test