name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  core-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-core-${{ hashFiles('**/Cargo.lock') }}

      - name: Core tests
        run: cargo test --package sentc-crypto-core test

  std-keys-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-core-${{ hashFiles('**/Cargo.lock') }}

      - name: Std keys tests
        run: cargo test --package sentc-crypto-std-keys --lib test --features=full

  fips-keys-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-core-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

      - name: Cache OpenSSL build
        id: openssl-cache
        uses: actions/cache@v3
        with:
          path: /usr/local/openssl-3.3-fips
          key: openssl-3.3-fips-${{ runner.os }}-${{ hashFiles('openssl-3.3.0.tar.gz') }}
          restore-keys: |
            openssl-3.3-fips-${{ runner.os }}-

      - name: Download OpenSSL 3.3
        if: steps.openssl-cache.outputs.cache-hit != 'true'
        run: |
          curl -O https://www.openssl.org/source/openssl-3.3.0.tar.gz
          tar -xzf openssl-3.3.0.tar.gz
          cd openssl-3.3.0

      - name: Configure and Build OpenSSL 3.3 with FIPS mode
        if: steps.openssl-cache.outputs.cache-hit != 'true'
        run: |
          cd openssl-3.3.0
          ./Configure enable-fips linux-x86_64 --prefix=/usr/local/openssl-3.3-fips
          make
          sudo make install

      - name: Set OpenSSL environment variables
        run: |
          echo "OPENSSL_DIR=/usr/local/openssl-3.3-fips" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=/usr/local/openssl-3.3-fips/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/usr/local/openssl-3.3-fips/include" >> $GITHUB_ENV
          echo "/usr/local/openssl-3.3-fips/lib" | sudo tee -a /etc/ld.so.conf.d/openssl-3.3-fips.conf
          sudo ldconfig

      - name: Verify OpenSSL version
        run: |
          openssl version -a

      - name: Fips keys tests
        run: cargo test --package sentc-crypto-fips-keys --lib test --features=full

  crypto-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-crypto_default-${{ hashFiles('**/Cargo.lock') }}

      - name: Crypto default tests
        run: cargo test --package sentc-crypto --lib test --features=server,export

  crypto-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-crypto_rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Crypto rust tests
        run: cargo test --package sentc-crypto --lib test --features=server

  crypto-light-default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-crypto_rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Crypto light default tests
        run: cargo test --package sentc-crypto-light --lib test --features=export

  crypto-light-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-crypto_rust-${{ hashFiles('**/Cargo.lock') }}

      - name: Crypto light rust tests
        run: cargo test --package sentc-crypto-light --lib test